package org.nuunframework.kernel.plugin.request.builders;

public interface BindingRequestBuilderOptionsBuildMain extends BindingRequestBuilderMain, BindingRequestBuilderOptions, BindingRequestBuilderBuild
{
}